services:
  app:
    container_name: kx-backend
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      APP_ENV: prod
      DATABASE_URL: ${PROD_DATABASE_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}