services:
  app:
    container_name: kx-backend
    build: .
    ports:
      - "8080:8080"
    restart: no
    environment:
      APP_ENV: dev
      DATABASE_URL: ${DEV_DATABASE_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}