"""Claude API 호출

— 시나리오+장르+고급설정(+레퍼런스 이미지)로 9컷 통합 영문 프롬프트 생성."""

import logging

import anthropic

from app.ai.base import PromptAdapter
from app.ai.exceptions import (
    RETRYABLE_STATUS_CODES,
    AIAdapterError,
    AIAdapterRequestError,
    AIAdapterTimeoutError,
    AIAdapterUnavailableError,
)
from app.ai.retry import call_with_retry
from app.core.config import get_settings
from app.core.enums import Genre

logger = logging.getLogger(__name__)

# 테스트에서 응답이 중간에 잘려서(stop_reason=max_tokens) 재시도 낭비된 사례 있어서 상향
MAX_TOKENS = 2500

# 기본적으로 PRD 문서에서 뽑아낸 규칙들 영문으로 넣어놓음
# + 글자수: 전체 3000자 하드 리밋 + 샷당 240자(샷당 제한 조절 테스트중)
# + 샷별 설명 순서: Camera -> Subject -> Action -> Setting -> Lighting -> Style
# + 색상 일관성: 특정 샷만 흑백인 버그 있었음. "9컷 전부 같은 컬러(기본 풀컬러)" 강제.
# + 인물 일관성: 동일하진 못해도 등장인물의 간단한 특징을 고정문구로 지정 → 명사형 쉼표로 축소
# + 인물 묘사를 반복해야 하는 이유도 추가(9컷이 서로 보지 못한다)
# + 같은 장소면 건축적 디테일(벽/바닥/조명)도 유지하라고 추가
# + 다음 샷이랑 카메라 앵글 안 겹치게(장르별 프리셋 전까지 가벼운 조치)
# + 화풍 일관성: 실사와 카툰이 섞여 나오는 버그 있었음 → 명사형 고정 추가
# + 화풍 기본값: style 없으면 photorealistic 기본(임시) → style enum 생각중
# + 아직 미확정 추후 기능: 장르별 프리셋, 고급설정 → 넣게되면 프롬프트 수정필요

SYSTEM_PROMPT = """You are a cinematography prompt writer for an AI storyboard tool.

Given a scenario and genre/style settings (and optionally reference images of characters,
backgrounds, or props), write an integrated English prompt for exactly 9 sequential shots
that visually tell the scenario as a storyboard.

Output format (strict):
- Output ONLY the 9 shots, labeled "Shot 1:" through "Shot 9:", one per paragraph.
- No preamble, no explanation, no markdown headers or bullet points — just the 9 labeled shots.
- English only, regardless of the input language.
- HARD LIMIT: all 9 shots combined must stay under 3000 characters total. This is the single
  most important constraint — if you are unsure whether you are within budget, write shorter
  shots rather than risk going over.

Each shot must describe, in this order: Camera -> Subject -> Action -> Setting -> Lighting -> Style.
- Camera: an explicit angle name + camera position + the resulting visual effect
  (e.g. "low-angle, camera positioned near the ground looking upward, subject appears imposing").
  Never leave the angle vague or implicit. Avoid repeating the exact same angle in two
  immediately consecutive shots so the sequence doesn't feel visually repetitive — reusing an
  angle after a gap of a shot or two is fine if the moment calls for it.
- Action: exactly one present-tense verb, one single action.
- Do not use abstract mood words (e.g. "dynamic", "various", "dramatic", "beautiful") —
  image models blur these into nothing. Describe concrete, visible details instead.
- HARD PER-SHOT CEILING: each shot must be under 240 characters (roughly 30-35 words) — this
  already accounts for a repeated character trait phrase taking up part of that budget. Do the
  math as you write: 9 shots x 240 characters = 2160, leaving real margin under the 3000-character
  hard limit above — that margin is a safety buffer, not room to write longer shots. If a shot
  draft runs long, cut adjectives and shorten clauses before moving to the next shot rather than
  carrying the overage forward. A shot that reads terse and plain is correct; a shot that reads
  rich and detailed is very likely too long.
- All 9 shots must share the exact same color treatment — full color by default. Never let a
  single shot go black-and-white/monochrome/sepia while the others stay in color (or vice versa),
  even when a shot's mood/genre words (e.g. "noir") might tempt you toward it. A stylized grade
  (e.g. desaturated, high-contrast lighting) is fine, but apply it identically to all 9 shots —
  only go fully black-and-white for every shot together, and only if era/style explicitly
  requires it (e.g. a period piece explicitly described as black-and-white film).
- Rendering style consistency is just as critical, and fails for the exact same reason as color:
  decide on ONE single-word rendering-style tag up front based on the given style/genre/tone
  (e.g. "photorealistic" or "cartoon" or "anime" — one word, not a descriptive phrase). If no
  style is given, default to "photorealistic" unless the scenario itself clearly calls for
  something else (e.g. an explicitly whimsical fairy-tale premise) — a comedic or lighthearted
  genre/tone alone is NOT reason enough to switch away from photorealistic. Then end every single
  one of the 9 shots with that EXACT SAME tag, word-for-word. Never let some shots read as
  photorealistic while others read as cartoon/animated/illustrated — express comedic or
  exaggerated tone through action and expression, not by switching the rendering style itself.
  Each shot is generated by an isolated image call with no memory of the other 8 shots, so a shot
  that doesn't explicitly restate the style tag may default to a completely different rendering
  style than the rest.
- Character consistency is required in every case, not only when reference images are provided:
  if the scenario names or clearly identifies any character(s), the first time each character
  appears, establish their key visible traits (approximate age, hair, outfit, distinguishing
  features) in a SHORT fixed phrase of 5-6 words MAXIMUM — a comma-separated tag list, not a full
  descriptive clause (e.g. "mid-30s, short black hair, gray jacket", NOT "a mid-30s man with short
  black hair and a gray running jacket"). Then repeat that EXACT SAME short phrase word-for-word
  every time that character appears in a later shot — do not paraphrase or vary the wording even
  slightly (e.g. "dark trench coat" must not later become "black coat" or "long coat"). Identical
  wording across shots is required, not just similar meaning. This phrase repeats up to 9 times
  across the whole prompt, so every word you trim from it multiplies across all 9 shots — keep it
  as short as possible while still visually distinguishing this character from any other character
  in the scenario.
  CRITICAL REASON for this rule: each shot's text is sent to an image generator IN ISOLATION —
  whichever shot generates later never sees any earlier shot. A shot that only names a character
  (e.g. "the detective runs inside") without repeating their trait phrase gives the image
  generator zero information about what that character looks like, so it will render a
  random-looking person. Naming a character is NEVER a substitute for repeating their trait
  phrase — every shot that character appears in, however minor their role in that shot, must
  still carry the full phrase.
- If reference images are provided, ground that same consistency in what is actually shown in
  those images (appearance, background, props) instead of inventing new traits.
- Location/setting consistency: if multiple shots take place in or around the same physical
  location, treat it as one continuous place, not a new one each time — keep material and
  structural details (wall/floor material, color palette, fixture and lighting types) identical
  across those shots even as the camera moves to a different part of it or the framing changes.
- Reflect the given genre/tone/era through concrete visual language in the Subject/Action/Setting/
  Lighting parts of each shot (not by naming the setting fields directly) — this is about what the
  shot shows, separate from the rendering-style phrase above, which is about how it is rendered.
"""


def _build_user_content(
    *,
    scenario_text: str,
    genre: Genre,
    style: str | None,
    tone: str | None,
    aspect_ratio: str | None,
    era: str | None,
    reference_image_urls: list[str],
) -> list[anthropic.types.TextBlockParam | anthropic.types.ImageBlockParam]:
    """Claude한테 보낼 사용자 메시지 내용"""
    settings_lines = [f"Genre: {genre}"]
    if style:
        settings_lines.append(f"Style: {style}")
    if tone:
        settings_lines.append(f"Tone: {tone}")
    if era:
        settings_lines.append(f"Era: {era}")
    if aspect_ratio:
        settings_lines.append(f"Aspect ratio: {aspect_ratio}")

    text = f"Scenario:\n{scenario_text}\n\nSettings:\n" + "\n".join(settings_lines)

    content: list[anthropic.types.TextBlockParam | anthropic.types.ImageBlockParam] = [
        {"type": "text", "text": text}
    ]
    for url in reference_image_urls:
        content.append({"type": "image", "source": {"type": "url", "url": url}})
    return content


def _map_error(exc: anthropic.AnthropicError) -> AIAdapterError:
    """anthropic SDK가 던지는 에러를 exceptions.py 형식으로 바꾸기"""
    if isinstance(exc, anthropic.APITimeoutError):
        return AIAdapterTimeoutError(str(exc))
    if isinstance(exc, anthropic.APIConnectionError):
        return AIAdapterUnavailableError(str(exc))
    if isinstance(exc, anthropic.APIStatusError):
        if exc.status_code in RETRYABLE_STATUS_CODES:
            return AIAdapterUnavailableError(str(exc))
        return AIAdapterRequestError(str(exc))
    return AIAdapterError(str(exc))


class ClaudePromptAdapter(PromptAdapter):
    def __init__(self, client: anthropic.Anthropic | None = None, model: str | None = None) -> None:
        """테스트 때문에 client나 model이 없는 경우를 넣어놓음"""
        if client is None or model is None:
            settings = get_settings()
            client = client or anthropic.Anthropic(api_key=settings.anthropic_api_key)
            model = model or settings.anthropic_model
        self._client = client
        self._model = model

    def generate_prompt(
        self,
        *,
        scenario_text: str,
        genre: Genre,
        style: str | None = None,
        tone: str | None = None,
        aspect_ratio: str | None = None,
        era: str | None = None,
        reference_image_urls: list[str] | None = None,
    ) -> str:
        content = _build_user_content(
            scenario_text=scenario_text,
            genre=genre,
            style=style,
            tone=tone,
            aspect_ratio=aspect_ratio,
            era=era,
            reference_image_urls=reference_image_urls or [],
        )

        def _call() -> str:
            """API 호출 시도"""
            try:
                message = self._client.messages.create(
                    model=self._model,
                    max_tokens=MAX_TOKENS,
                    # SYSTEM_PROMPT가 모든 호출에서 동일해서 캐싱 대상
                    # 캐시 유효 시간 내 반복 호출 시 토큰 비용 절감
                    # 개발 테스트 호출 간격이 뜨문뜨문이라 5분 대신 1시간 TTL 설정
                    # (실서비스 트래픽때는 5분 캐싱으로 바꾸는게 가격적 이득)
                    system=[
                        {
                            "type": "text",
                            "text": SYSTEM_PROMPT,
                            "cache_control": {"type": "ephemeral", "ttl": "1h"},
                        }
                    ],
                    messages=[{"role": "user", "content": content}],
                )
            except anthropic.AnthropicError as exc:
                raise _map_error(exc) from exc

            # 캐시 실제 히트 확인용 — cache_read면 캐시 탐, cache_creation이면 새로 씀
            logger.warning( # 실서비스땐 info로 변경, logging.basicConfig(level=logging.INFO) 추가
                "claude usage: input=%d cache_creation=%d cache_read=%d output=%d",
                message.usage.input_tokens,
                message.usage.cache_creation_input_tokens or 0,
                message.usage.cache_read_input_tokens or 0,
                message.usage.output_tokens,
            )

            if message.stop_reason == "max_tokens":
                raise AIAdapterError(
                    f"Claude 응답이 max_tokens({MAX_TOKENS})에서 잘렸습니다 — "
                    "프롬프트 길이 또는 MAX_TOKENS 조정이 필요합니다."
                )

            return "".join(block.text for block in message.content if block.type == "text")
            # message.content 순회하면서 type이 text인 블록들의 텍스트만 이어붙여서 최종 문자열로 반환

        return call_with_retry(_call, label="claude_prompt_adapter")
        # call_with_retry 함수는 API 부를때마다 쓰이지만 반복(재시도) 동작은 문제 생겼을때만
